project: ddpg_scaling
name: test1

# model related
batch_size: 128
actor_layers: [128, 128, 128]
critic_layers: [128, 128, 128]
actor_lr: 1.0e-4
critic_lr: 1.0e-3

# agent
gamma: 0.99
tau': 1.0e-2
activation': sigmoid
noise_mu: 0.0 
noise_theta: 0.15 
noise_max_sigma: 0.3 
noise_min_sigma: 0.3

# memory
memory_size: 50000

# environment
# ......

# training
# ......
train_epochs: 20
train_steps: 20000

log_epochs: 1
eval_epochs: 10
save_epochs: 20
show_epochs: 30
